apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nagp-ecom
  labels:
    app: nagp-ecom
    type: ingress
    stack: nagp-ecom
  annotations:
    # nginx CONFIG
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/use-regex: "true"
    # traefik CONFIG
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.pathmatcher: PathRegex
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          # - path: '/api'
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: nagp-app-api
          #       port:
          #         number: 80
          # # I have a scalar service that I want to expose on api
          # - path: "/(scalar|openapi)(/|$)"
          #   pathType: ImplementationSpecific
          #   backend:
          #     service:
          #       name: nagp-app-api
          #       port:
          #         number: 80
          # all other requests should go to the UI service
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: nagp-ecom-ui
                port:
                  number: 80