apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $.Values.project | quote }}
  namespace: argocd
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  destinations:
  - name: defaultCluster
    namespace: {{ $.Release.Namespace }}
    server: {{ $.Values.config.spec.destination.server | quote }}
  sourceRepos:
  - {{ $.Values.config.spec.source.repoURL }}