apiVersion: v1
kind: Secret
metadata:
  name: local-selfsigned-tls
  namespace: traefik
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDGzCCAgOgAwIBAgIUOTLdSk81yHwnp5ygIYfpwv5HDKcwDQYJKoZIhvcNAQEL
    BQAwHTEbMBkGA1UEAwwSKi5kb2NrZXIubG9jYWxob3N0MB4XDTI2MDEwNDE0MjIx
    NVoXDTI3MDEwNDE0MjIxNVowHTEbMBkGA1UEAwwSKi5kb2NrZXIubG9jYWxob3N0
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6TH6qHqK+V5jVmr/iNeI
    pZYE1mtLslQsduTnzNB3RDJq++SXT5CkKA3q8UZ2KXzK1Pmt8W1YeafZM1UbJEKO
    gepcATla3ApFZ3UnPRcnFI9GCUrux8vrb6GIWzPhrn1dmFSbNq33EeqdJOADL7O5
    mJOAxkRWxGy7l9dT4VIYYMyuRwW2QDqNYBy9wlwqHDbLyBg6igQE4YRe/B1QKraU
    7tAzhtvSiaV9QTBkxgIAwC7tzON9duegk9TcKuVb/QYfg09a7hjT6X/JxnhdBpVi
    jlPO2ynHNTHyn1oE4fh5Cu9p5cCPfQjWjaYp826nhcNAAUEoClMDgySrB+klTnqa
    jwIDAQABo1MwUTAdBgNVHQ4EFgQUpMDKGIJb9fdc2LUjwcVDmwktQqIwHwYDVR0j
    BBgwFoAUpMDKGIJb9fdc2LUjwcVDmwktQqIwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAQEAFp5B2B0534EXaeXUAl1acLSrhtOkv6ITEC03Q2+0N71L
    ieFj9x9/W9DDlTZj7pNE4O2/D3uscQpi4If8ucQ1iYXiO0M+IkSdAci23EubCAEv
    EIZ2tLnl0D11H0/0Q3juD/0fIhsl3MARBivC0+MhA3sVxs/fhBJ2AaMUYjJ/M+3h
    Ru/G9QEhETgJJlCrAhNnYm93vSnzoDUeqmMbveC0ZIYotDtPSrZDw+afILBRnRRF
    JXGbKMt4gUQbTxAd52KDRFiSeiRelxRAX6IRFODR6/7Q6fthWjbgkyw+46fPCwGw
    phVLvwGG/uClvH/PSFK42wBVmkCQ+wz6wb8hH0uddQ==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDpMfqoeor5XmNW
    av+I14illgTWa0uyVCx25OfM0HdEMmr75JdPkKQoDerxRnYpfMrU+a3xbVh5p9kz
    VRskQo6B6lwBOVrcCkVndSc9FycUj0YJSu7Hy+tvoYhbM+GufV2YVJs2rfcR6p0k
    4AMvs7mYk4DGRFbEbLuX11PhUhhgzK5HBbZAOo1gHL3CXCocNsvIGDqKBAThhF78
    HVAqtpTu0DOG29KJpX1BMGTGAgDALu3M431256CT1Nwq5Vv9Bh+DT1ruGNPpf8nG
    eF0GlWKOU87bKcc1MfKfWgTh+HkK72nlwI99CNaNpinzbqeFw0ABQSgKUwODJKsH
    6SVOepqPAgMBAAECggEATIAAXl/hEoCD7xgn30Dxy3yE9sB5MzXI5nIelwK2dZFi
    pmLtvoTRTXCPZ/p5DhApzCdiiEaaVUKajuv2/PS2omj7KM2jgHcAILn+ltxvDiAY
    VjkWT0YW5OalgGHrQd5Po4bx6kS0vlRsm+m/MdlwY9zTzHcjzclr2xqhIlRXuf0b
    IOfulEWRuo5kpcdzn3QQT83cK6UKsn7Whv2XWrmany2uweN35FnmYlfQuIeYYe4w
    N0gzacFFpy2hohFpBng9c5qhb0bNuB8Pk0zERqv204qyOuCvU8Wf37NoTDSS347n
    gNHuyLoQV/Yy8KBQ6rsCIISUFxorhTtdxJkd9f0liQKBgQD/g1vS58na08L56gwn
    0aR9fuV4TpsTlE1+J/U7K13N+lr5Mnglddm8HYkW7ONR6njJe8/LVWp4HXToDlCG
    7ZLS0ugZLzBtC6Bzlhs04UxpPFe3n99ZrH4JZh/rbG+s1K0VYzhEb3BF0BHXGvnH
    XXxqKcIw4BhQp+NddONgH/rCqQKBgQDpo7vNfkSOqIWRwtGaS2KK61NNMhP8eF2n
    aHXCxissmQrU005b15z5WDWzwhlwWGF/VgsSmRPDGLcFip8qqbxHsiKHFrcL2r/W
    8x1ni+qxOkuDzRJ/Px3UjHYVDtwR9QWbvIV/617QetIkK9J3U0fX2pJQQLyilhxr
    mU+ZuAnudwKBgQCgdxiFvXexa+g5F1mG8EwDXFw0T/loNGzuW53RCQ0iPKZBdgaq
    T/bsAwiDU0X3ve8Zah43rm7s/GLdEZBVDIJ20Gle15nsAa9Ep/JyJUPdmz3jXg3g
    vUlyEabeLP19ZxtEIUnHAM1bqq5pjtFq+TUXXx5Ln5DlpmpN2Qiq56qN8QKBgDSV
    c0k2p/trllROApq1aMJXYHI5WSIzfPCWpBpoO4NYFoX74ODu0BeWcM+6WbtdSOQ9
    21QeO8JnJ5oJrvUNKqEASKEazavPWeno4a9SYEnvEtvhJc6Zx/70dgcbRxCLku2Q
    KoO116sYWX9mlYHhroO4X8HMMChvnInjAXVZZHLVAoGBAL9aFoMgkNW/dwSa17hN
    BAQqZhkI6sLCrJ/br/a3iRUBH2IsozOzQ9OpoNZdrljv/+gKxdrOlu47N8tXS2Yw
    XpGgJ7cc+2NzUZz2AesN8zHfkOHaN2ovrKStrJXyIMWZHOEdDo/t+g0N4WcUKCc3
    qv6iB6+yEbMUjvNnQHSSkHAR
    -----END PRIVATE KEY-----

